repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# Formats code correctly
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        args: [
            '--experimental-string-processing'
        ]

# Sorts imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]

# Checks unused imports, like lengths, etc
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.0
    hooks:
    -   id: flake8
        args: [
            '--per-file-ignores=__init__.py:F401',
            '--max-line-length=88',
            '--ignore=E203,W503'
        ]

# Checks types
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    -   id: mypy
        additional_dependencies: [data-science-types>=0.2, torch>=1.6]
